### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by kajm** [dailymotion/salad-ui#6]
When trying to use your circlepie with React 16 it just crashes. When going back to React 15 it all works well, so i was thinking that you do not support React 16 just yet. 
Is there any plans to support it?

**Comment by samueldelesque** [comment]
Please submit your request here https://github.com/samueldelesque/salad-ui - Dailymotion isn't maintaining this repo any longer.

**Comment by samueldelesque** [comment]
@kajm Actually just update to the latest npm package and you should be all set!

**Comment by kajm** [comment]
@samueldelwsque great! I will have another try later then! Thanks!
